version: 0.2

phases:
  install:
    commands:
      - pip install -r requirements.txt  # Instalar dependencias
  pre_build:
    commands:
      - echo Running tests...  # Mensaje para mostrar en el log
  build:
    commands:
      - pytest --maxfail=1 --disable-warnings --tb=short  # Ejecutar pruebas, detener al primer fallo, ocultar advertencias y mostrar traceback corto
  post_build:
    commands:
     - |
      if [ "$CODEBUILD_BUILD_SUCCEEDING" == "0" ]; then
        echo "Build fallido, no se empacará ni se subirá nada."
        exit 1
      fi
      - echo "Empaquetando artefacto..."
      - zip -r artifact.zip .
      - echo "Subiendo artifact.zip a S3..."
      - aws s3 cp artifact.zip s3://bucket-deploy-1-1/artifact.zip

artifacts:
  files:
    - artifact.zip
